import type { DndRace, DndClass, DndBackground, Skill, Spell } from '@shared/types';
export const RACES: DndRace[] = [
  {
    name: 'Human',
    description: 'Humans are the most adaptable and ambitious people among the common races. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Strength: 1, Dexterity: 1, Constitution: 1, Intelligence: 1, Wisdom: 1, Charisma: 1 },
  },
  {
    name: 'Elf',
    description: 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it. They live in places of ethereal beauty, in the midst of ancient forests or in silvery spires glittering with faerie light.',
    imageUrl: 'https://images.unsplash.com/photo-1632543598041-b9d7a19753a3?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Dexterity: 2 },
  },
  {
    name: 'Dwarf',
    description: 'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. Though they stand well under a meter tall, dwarves are so broad and compact that they can weigh as much as a human standing nearly two feet taller.',
    imageUrl: 'https://images.unsplash.com/photo-1621966255392-d2f1f8b361d7?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Constitution: 2 },
  },
  {
    name: 'Halfling',
    description: 'The comforts of home are the goals of most halflings’ lives: a place to settle in peace and quiet, far from marauding monsters and clashing armies; a blazing fire and a generous meal; fine drink and fine conversation.',
    imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Dexterity: 2 },
  },
  {
    name: 'Dragonborn',
    description: 'Born of dragons, as their name proclaims, the dragonborn walk proudly through a world that greets them with fearful incomprehension. Shaped by draconic gods or the dragons themselves, dragonborn originally hatched from dragon eggs as a unique race.',
    imageUrl: 'https://images.unsplash.com/photo-1615011992922-3f39343356a1?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Strength: 2, Charisma: 1 },
  },
  {
    name: 'Gnome',
    description: 'A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body. Gnomes average slightly over 3 feet tall and weigh 40 to 45 pounds. Their tan or brown faces are usually adorned with broad smiles.',
    imageUrl: 'https://images.unsplash.com/photo-1507332159745-89348a0a1975?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Intelligence: 2 },
  },
  {
    name: 'Half-Elf',
    description: 'Walking in two worlds but truly belonging to neither, half-elves combine what some say are the best qualities of their elf and human parents: human curiosity, inventiveness, and ambition tempered by the refined senses, love of nature, and artistic tastes of the elves.',
    imageUrl: 'https://images.unsplash.com/photo-1551887999-48e2a0a08533?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Charisma: 2 }, // Plus two others of choice, simplified for SRD
  },
  {
    name: 'Half-Orc',
    description: 'Whether united under the leadership of a mighty warlock or having fought their way out of servitude, half-orcs must constantly strive to prove their worth. Some live for the glory of battle and the din of steel. Others prove their worth by acts of piety and goodness.',
    imageUrl: 'https://images.unsplash.com/photo-1604176422397-734c383a3a32?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Strength: 2, Constitution: 1 },
  },
  {
    name: 'Tiefling',
    description: 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling. And to twist the knife, tieflings know that this is because a pact struck generations ago infused the essence of Asmodeus into their bloodline.',
    imageUrl: 'https://images.unsplash.com/photo-1617293541285-33375832ab60?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    abilityScoreIncrease: { Intelligence: 1, Charisma: 2 },
  },
];
export const SPELLS: Spell[] = [
  // Cantrips (Level 0)
  { name: 'Acid Splash', level: 0, description: 'You hurl a bubble of acid.' },
  { name: 'Blade Ward', level: 0, description: 'You extend your hand and trace a sigil of warding in the air.' },
  { name: 'Chill Touch', level: 0, description: 'You create a ghostly, skeletal hand in the space of a creature within range.' },
  { name: 'Dancing Lights', level: 0, description: 'You create up to four torch-sized lights within range.' },
  { name: 'Druidcraft', level: 0, description: 'You create a tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours.' },
  { name: 'Eldritch Blast', level: 0, description: 'A beam of crackling energy streaks toward a creature within range.' },
  { name: 'Fire Bolt', level: 0, description: 'You hurl a mote of fire at a creature or object within range.' },
  { name: 'Guidance', level: 0, description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.' },
  { name: 'Light', level: 0, description: 'You touch one object... it sheds bright light in a 20-foot radius.' },
  { name: 'Mage Hand', level: 0, description: 'A spectral, floating hand appears at a point you choose within range.' },
  { name: 'Mending', level: 0, description: 'This spell repairs a single break or tear in an object you touch.' },
  { name: 'Minor Illusion', level: 0, description: 'You create a sound or an image of an object within range that lasts for the duration.' },
  { name: 'Poison Spray', level: 0, description: 'You extend your hand toward a creature you can see within range and project a puff of noxious gas from your palm.' },
  { name: 'Prestidigitation', level: 0, description: 'This spell is a minor magical trick that novice spellcasters use for practice.' },
  { name: 'Produce Flame', level: 0, description: 'A flickering flame appears in your hand.' },
  { name: 'Ray of Frost', level: 0, description: 'A frigid beam of blue-white light streaks toward a creature within range.' },
  { name: 'Resistance', level: 0, description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice.' },
  { name: 'Sacred Flame', level: 0, description: 'Flame-like radiance descends on a creature that you can see within range.' },
  { name: 'Shillelagh', level: 0, description: 'The wood of a club or quarterstaff you are holding is imbued with nature’s power.' },
  { name: 'Shocking Grasp', level: 0, description: 'Lightning springs from your hand to deliver a shock to a creature you try to touch.' },
  { name: 'Thaumaturgy', level: 0, description: 'You manifest a minor wonder, a sign of supernatural power, within range.' },
  { name: 'True Strike', level: 0, description: 'You extend your hand and point a finger at a target in range.' },
  { name: 'Vicious Mockery', level: 0, description: 'You unleash a string of insults laced with subtle enchantments at a creature you can see within range.' },
  // 1st Level
  { name: 'Animal Friendship', level: 1, description: 'This spell lets you convince a beast that you mean it no harm.' },
  { name: 'Armor of Agathys', level: 1, description: 'A protective magical force surrounds you, manifesting as a spectral frost that covers you and your gear.' },
  { name: 'Bane', level: 1, description: 'Up to three creatures of your choice that you can see within range must make Charisma saving throws.' },
  { name: 'Bless', level: 1, description: 'You bless up to three creatures of your choice within range.' },
  { name: 'Burning Hands', level: 1, description: 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips.' },
  { name: 'Charm Person', level: 1, description: 'You attempt to charm a humanoid you can see within range.' },
  { name: 'Command', level: 1, description: 'You speak a one-word command to a creature you can see within range.' },
  { name: 'Comprehend Languages', level: 1, description: 'For the duration, you understand the literal meaning of any spoken language that you hear.' },
  { name: 'Create or Destroy Water', level: 1, description: 'You either create or destroy water.' },
  { name: 'Cure Wounds', level: 1, description: 'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.' },
  { name: 'Detect Evil and Good', level: 1, description: 'For the duration, you know if there is an aberration, celestial, elemental, fey, fiend, or undead within 30 feet of you.' },
  { name: 'Detect Magic', level: 1, description: 'For the duration, you sense the presence of magic within 30 feet of you.' },
  { name: 'Detect Poison and Disease', level: 1, description: 'For the duration, you can sense the presence and location of poisons, poisonous creatures, and diseases within 30 feet of you.' },
  { name: 'Disguise Self', level: 1, description: 'You make yourself���including your clothing, armor, weapons, and other belongings on your person—look different until the spell ends or until you use your action to dismiss it.' },
  { name: 'Entangle', level: 1, description: 'Grasping weeds and vines sprout from the ground in a 20-foot square starting from a point within range.' },
  { name: 'Expeditious Retreat', level: 1, description: 'This spell allows you to move at an incredible pace.' },
  { name: 'Faerie Fire', level: 1, description: 'Each object in a 20-foot cube within range is outlined in blue, green, or violet light (your choice).' },
  { name: 'False Life', level: 1, description: 'Bolstering yourself with a necromantic facsimile of life, you gain 1d4 + 4 temporary hit points for the duration.' },
  { name: 'Feather Fall', level: 1, description: 'Choose up to five falling creatures within range. A falling creature’s rate of descent slows to 60 feet per round until the spell ends.' },
  { name: 'Find Familiar', level: 1, description: 'You gain the service of a familiar, a spirit that takes an animal form you choose.' },
  { name: 'Fog Cloud', level: 1, description: 'You create a 20-foot-radius sphere of fog centered on a point within range.' },
  { name: 'Goodberry', level: 1, description: 'Up to ten berries appear in your hand and are infused with magic for the duration.' },
  { name: 'Grease', level: 1, description: 'Slick grease covers the ground in a 10-foot square centered on a point within range and turns it into difficult terrain for the duration.' },
  { name: 'Guiding Bolt', level: 1, description: 'A flash of light streaks toward a creature of your choice within range.' },
  { name: 'Healing Word', level: 1, description: 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.' },
  { name: 'Hellish Rebuke', level: 1, description: 'You point your finger, and the creature that damaged you is momentarily surrounded by hellish flames.' },
  { name: 'Heroism', level: 1, description: 'A willing creature you touch is imbued with bravery.' },
  { name: 'Hideous Laughter', level: 1, description: 'A creature of your choice that you can see within range perceives everything as hilariously funny and falls into fits of laughter if this spell affects it.' },
  { name: 'Hunter\'s Mark', level: 1, description: 'You choose a creature you can see within range and mystically mark it as your quarry.' },
  { name: 'Identify', level: 1, description: 'You choose one object that you must touch throughout the casting of the spell.' },
  { name: 'Illusory Script', level: 1, description: 'You write on parchment, paper, or some other suitable writing material and imbue it with a potent illusion that lasts for the duration.' },
  { name: 'Inflict Wounds', level: 1, description: 'Make a melee spell attack against a creature you can reach.' },
  { name: 'Jump', level: 1, description: 'You touch a creature. The creature’s jump distance is tripled until the spell ends.' },
  { name: 'Longstrider', level: 1, description: 'You touch a creature. The target’s speed increases by 10 feet until the spell ends.' },
  { name: 'Mage Armor', level: 1, description: 'You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.' },
  { name: 'Magic Missile', level: 1, description: 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range.' },
  { name: 'Protection from Evil and Good', level: 1, description: 'Until the spell ends, one willing creature you touch is protected against certain types of creatures.' },
  { name: 'Purify Food and Drink', level: 1, description: 'All nonmagical food and drink within a 5-foot-radius sphere centered on a point of your choice within range is purified and rendered free of poison and disease.' },
  { name: 'Sanctuary', level: 1, description: 'You ward a creature within range against attack.' },
  { name: 'Shield', level: 1, description: 'An invisible barrier of magical force appears and protects you.' },
  { name: 'Shield of Faith', level: 1, description: 'A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.' },
  { name: 'Silent Image', level: 1, description: 'You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 15-foot cube.' },
  { name: 'Sleep', level: 1, description: 'This spell sends creatures into a magical slumber.' },
  { name: 'Speak with Animals', level: 1, description: 'You gain the ability to comprehend and verbally communicate with beasts for the duration.' },
  { name: 'Thunderwave', level: 1, description: 'A wave of thunderous force sweeps out from you.' },
  { name: 'Unseen Servant', level: 1, description: 'This spell creates an invisible, mindless, shapeless force that performs simple tasks at your command until the spell ends.' },
  { name: 'Witch Bolt', level: 1, description: 'A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target.' },
];
export const CLASSES: DndClass[] = [
  {
    name: 'Barbarian',
    description: 'A fierce warrior of primitive background who can enter a battle rage.',
    imageUrl: 'https://images.unsplash.com/photo-1599493356233-83a54d954475?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 12,
    savingThrowProficiencies: ['Strength', 'Constitution'],
    skillProficiency: {
      count: 2,
      choices: ['Animal Handling', 'Athletics', 'Intimidation', 'Nature', 'Perception', 'Survival'],
    },
    startingEquipment: ['Greataxe', 'Two Handaxes', 'Explorer\'s Pack', 'Four Javelins'],
  },
  {
    name: 'Bard',
    description: 'An inspiring magician whose power echoes the music of creation.',
    imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106945?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 8,
    savingThrowProficiencies: ['Dexterity', 'Charisma'],
    skillProficiency: {
      count: 3,
      choices: ['Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception', 'History', 'Insight', 'Intimidation', 'Investigation', 'Medicine', 'Nature', 'Perception', 'Performance', 'Persuasion', 'Religion', 'Sleight of Hand', 'Stealth', 'Survival'],
    },
    startingEquipment: ['Rapier', 'Diplomat\'s Pack', 'Lute', 'Leather Armor', 'Dagger'],
    spellcasting: {
      ability: 'Charisma',
      cantripsKnown: 2,
      spellsKnown: 4,
      spellList: ['Dancing Lights', 'Mage Hand', 'Minor Illusion', 'Vicious Mockery', 'Charm Person', 'Detect Magic', 'Healing Word', 'Hideous Laughter', 'Sleep', 'Thunderwave'],
    },
  },
  {
    name: 'Cleric',
    description: 'A priestly champion who wields divine magic in service of a higher power.',
    imageUrl: 'https://images.unsplash.com/photo-1587697939883-5356de88f189?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 8,
    savingThrowProficiencies: ['Wisdom', 'Charisma'],
    skillProficiency: {
      count: 2,
      choices: ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'],
    },
    startingEquipment: ['Mace', 'Scale Mail', 'Shield', 'Holy Symbol', 'Priest\'s Pack'],
    spellcasting: {
      ability: 'Wisdom',
      cantripsKnown: 3,
      spellsKnown: 2,
      spellList: ['Guidance', 'Light', 'Resistance', 'Sacred Flame', 'Thaumaturgy', 'Bane', 'Bless', 'Command', 'Cure Wounds', 'Guiding Bolt', 'Healing Word', 'Inflict Wounds', 'Protection from Evil and Good', 'Sanctuary', 'Shield of Faith'],
    },
  },
  {
    name: 'Druid',
    description: 'A priest of the Old Faith, wielding the powers of nature and adopting animal forms.',
    imageUrl: 'https://images.unsplash.com/photo-1621767828244-e23e91127329?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 8,
    savingThrowProficiencies: ['Intelligence', 'Wisdom'],
    skillProficiency: {
      count: 2,
      choices: ['Arcana', 'Animal Handling', 'Insight', 'Medicine', 'Nature', 'Perception', 'Religion', 'Survival'],
    },
    startingEquipment: ['Wooden Shield', 'Scimitar', 'Leather Armor', 'Explorer\'s Pack', 'Druidic Focus'],
    spellcasting: {
      ability: 'Wisdom',
      cantripsKnown: 2,
      spellsKnown: 2,
      spellList: ['Druidcraft', 'Guidance', 'Produce Flame', 'Shillelagh', 'Animal Friendship', 'Cure Wounds', 'Entangle', 'Faerie Fire', 'Fog Cloud', 'Goodberry', 'Healing Word', 'Speak with Animals', 'Thunderwave'],
    },
  },
  {
    name: 'Fighter',
    description: 'A master of martial combat, skilled with a variety of weapons and armor.',
    imageUrl: 'https://images.unsplash.com/photo-1598988935310-8de8709214db?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 10,
    savingThrowProficiencies: ['Strength', 'Constitution'],
    skillProficiency: {
      count: 2,
      choices: ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation', 'Perception', 'Survival'],
    },
    startingEquipment: ['Chain Mail', 'Longsword', 'Shield', 'Explorer\'s Pack'],
  },
  {
    name: 'Monk',
    description: 'A master of martial arts, harnessing the power of the body in pursuit of physical and spiritual perfection.',
    imageUrl: 'https://images.unsplash.com/photo-1578632201225-010182ab341a?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 8,
    savingThrowProficiencies: ['Strength', 'Dexterity'],
    skillProficiency: {
      count: 2,
      choices: ['Acrobatics', 'Athletics', 'History', 'Insight', 'Religion', 'Stealth'],
    },
    startingEquipment: ['Shortsword', 'Explorer\'s Pack', '10 Darts'],
  },
  {
    name: 'Paladin',
    description: 'A holy warrior bound to a sacred oath.',
    imageUrl: 'https://images.unsplash.com/photo-1600702179666-adef37586a1c?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 10,
    savingThrowProficiencies: ['Wisdom', 'Charisma'],
    skillProficiency: {
      count: 2,
      choices: ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'],
    },
    startingEquipment: ['Longsword', 'Shield', 'Chain Mail', 'Holy Symbol', 'Explorer\'s Pack'],
  },
  {
    name: 'Ranger',
    description: 'A warrior who uses martial prowess and nature magic to combat threats on the edges of civilization.',
    imageUrl: 'https://images.unsplash.com/photo-1520428122930-e4d628d3a7f4?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 10,
    savingThrowProficiencies: ['Strength', 'Dexterity'],
    skillProficiency: {
      count: 3,
      choices: ['Animal Handling', 'Athletics', 'Insight', 'Investigation', 'Nature', 'Perception', 'Stealth', 'Survival'],
    },
    startingEquipment: ['Scale Mail', 'Two Shortswords', 'Longbow and 20 Arrows', 'Explorer\'s Pack'],
  },
  {
    name: 'Rogue',
    description: 'A scoundrel who uses stealth and trickery to overcome obstacles and enemies.',
    imageUrl: 'https://images.unsplash.com/photo-1521587514354-cf4b355b5d24?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 8,
    savingThrowProficiencies: ['Dexterity', 'Intelligence'],
    skillProficiency: {
      count: 4,
      choices: ['Acrobatics', 'Athletics', 'Deception', 'Insight', 'Intimidation', 'Investigation', 'Perception', 'Performance', 'Persuasion', 'Sleight of Hand', 'Stealth'],
    },
    startingEquipment: ['Leather Armor', 'Two Daggers', 'Shortbow and 20 Arrows', 'Thieves\' Tools'],
  },
  {
    name: 'Sorcerer',
    description: 'A spellcaster who draws on inherent magic from a gift or bloodline.',
    imageUrl: 'https://images.unsplash.com/photo-1624720114708-0cbd6ee41f40?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 6,
    savingThrowProficiencies: ['Constitution', 'Charisma'],
    skillProficiency: {
      count: 2,
      choices: ['Arcana', 'Deception', 'Insight', 'Intimidation', 'Persuasion', 'Religion'],
    },
    startingEquipment: ['Light Crossbow and 20 bolts', 'Component Pouch', 'Dungeoneer\'s Pack', 'Two Daggers'],
    spellcasting: {
      ability: 'Charisma',
      cantripsKnown: 4,
      spellsKnown: 2,
      spellList: ['Acid Splash', 'Chill Touch', 'Fire Bolt', 'Light', 'Mage Hand', 'Prestidigitation', 'Ray of Frost', 'Shocking Grasp', 'Burning Hands', 'Charm Person', 'Detect Magic', 'Mage Armor', 'Magic Missile', 'Shield', 'Sleep'],
    },
  },
  {
    name: 'Warlock',
    description: 'A wielder of magic that is derived from a bargain with an extraplanar entity.',
    imageUrl: 'https://images.unsplash.com/photo-1631931413024-38ed4229d246?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 8,
    savingThrowProficiencies: ['Wisdom', 'Charisma'],
    skillProficiency: {
      count: 2,
      choices: ['Arcana', 'Deception', 'History', 'Intimidation', 'Investigation', 'Nature', 'Religion'],
    },
    startingEquipment: ['Light Crossbow and 20 bolts', 'Component Pouch', 'Scholar\'s Pack', 'Leather Armor', 'Dagger'],
    spellcasting: {
      ability: 'Charisma',
      cantripsKnown: 2,
      spellsKnown: 2,
      spellList: ['Chill Touch', 'Eldritch Blast', 'Mage Hand', 'Prestidigitation', 'Armor of Agathys', 'Charm Person', 'Hellish Rebuke', 'Witch Bolt'],
    },
  },
  {
    name: 'Wizard',
    description: 'A scholarly magic-user capable of manipulating the structures of reality.',
    imageUrl: 'https://images.unsplash.com/photo-1531822622333-a99e431c2e03?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    hitDie: 6,
    savingThrowProficiencies: ['Intelligence', 'Wisdom'],
    skillProficiency: {
      count: 2,
      choices: ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'],
    },
    startingEquipment: ['Spellbook', 'Dagger', 'Component Pouch', 'Scholar\'s Pack'],
    spellcasting: {
      ability: 'Intelligence',
      cantripsKnown: 3,
      spellsKnown: 2,
      spellList: ['Light', 'Mage Hand', 'Prestidigitation', 'Ray of Frost', 'Burning Hands', 'Detect Magic', 'Mage Armor', 'Magic Missile', 'Shield', 'Sleep'],
    },
  },
];
export const BACKGROUNDS: DndBackground[] = [
  { name: 'Acolyte', description: 'You have spent your life in the service of a temple to a specific god or pantheon of gods.', skillProficiencies: ['Insight', 'Religion'], startingEquipment: ['A holy symbol', 'A prayer book', '5 sticks of incense', 'Vestments', 'Common clothes', 'A belt pouch containing 15 gp'] },
  { name: 'Criminal', description: 'You are an experienced criminal with a history of breaking the law.', skillProficiencies: ['Deception', 'Stealth'], startingEquipment: ['A crowbar', 'A set of dark common clothes including a hood', 'A belt pouch containing 15 gp'] },
  { name: 'Folk Hero', description: 'You come from a humble social rank, but you are destined for so much more.', skillProficiencies: ['Animal Handling', 'Survival'], startingEquipment: ['A set of artisan\'s tools', 'A shovel', 'An iron pot', 'A set of common clothes', 'A belt pouch containing 10 gp'] },
  { name: 'Noble', description: 'You understand wealth, power, and privilege. You carry a noble title, and your family owns land, collects taxes, and wields significant political influence.', skillProficiencies: ['History', 'Persuasion'], startingEquipment: ['A set of fine clothes', 'A signet ring', 'A scroll of pedigree', 'A purse containing 25 gp'] },
  { name: 'Sage', description: 'You spent years learning the lore of the multiverse. You scoured manuscripts, studied scrolls, and listened to the greatest experts on the subjects that interest you.', skillProficiencies: ['Arcana', 'History'], startingEquipment: ['A bottle of black ink', 'A quill', 'A small knife', 'A letter from a dead colleague', 'A set of common clothes', 'A belt pouch containing 10 gp'] },
  { name: 'Soldier', description: 'War has been your life for as long as you care to remember. You trained as a youth, studied the use of weapons and armor, learned basic survival techniques, including how to stay alive on the battlefield.', skillProficiencies: ['Athletics', 'Intimidation'], startingEquipment: ['An insignia of rank', 'A trophy from a fallen enemy', 'A set of bone dice', 'A set of common clothes', 'A belt pouch containing 10 gp'] },
];
export const SKILLS: Skill[] = [
  // Strength
  { name: 'Athletics', ability: 'Strength' },
  // Dexterity
  { name: 'Acrobatics', ability: 'Dexterity' },
  { name: 'Sleight of Hand', ability: 'Dexterity' },
  { name: 'Stealth', ability: 'Dexterity' },
  // Intelligence
  { name: 'Arcana', ability: 'Intelligence' },
  { name: 'History', ability: 'Intelligence' },
  { name: 'Investigation', ability: 'Intelligence' },
  { name: 'Nature', ability: 'Intelligence' },
  { name: 'Religion', ability: 'Intelligence' },
  // Wisdom
  { name: 'Animal Handling', ability: 'Wisdom' },
  { name: 'Insight', ability: 'Wisdom' },
  { name: 'Medicine', ability: 'Wisdom' },
  { name: 'Perception', ability: 'Wisdom' },
  { name: 'Survival', ability: 'Wisdom' },
  // Charisma
  { name: 'Deception', ability: 'Charisma' },
  { name: 'Intimidation', ability: 'Charisma' },
  { name: 'Performance', ability: 'Charisma' },
  { name: 'Persuasion', ability: 'Charisma' },
];